### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by shantenujha** [SrinivasMushnoori/MolSSI_App#1]
! Package pdftex.def Error: File `repexscaling.png' not found.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.39 ...cs[width=0.55\textwidth]{repexscaling.png}

**Comment by SrinivasMushnoori** [comment]
Missing image file now  included. Please let me know if this has resolved the issue.
